### ISSUE TITLE
Possible bug in the gpu implementation of the nearest method.

### ISSUE THREAD

**Issue by dhorka** [rusty1s/pytorch_cluster#91]
Hello,

I was trying to port an old code that I have done in pytorch_geometric 1.3.1 and torch-cluster 1.4.4. I have found that with the current version of the nearest method, I am obtaining different output than the one obtained with the versions that I mentioned before. I am having this problem only in the GPU implementation; in fact, the CPU implementation of both versions is giving the same results. Besides the current implementation of the nearest method is giving me different results on CPU and GPU.You can find [here](https://drive.google.com/drive/folders/1hbaoIQhSPQ_vY9nrLwZABpD01keMjRk7?usp=sharing) the test that I have done and the data used for it. The data is a downsampled version of a scene from nyu_v2 dataset. This test file compares the different results on the GPU and CPU of the current version of the libraries. If needed, I can share with you the same test file for the older versions mentioned before.

**Comment by dhorka** [comment]
Hi,

I am just clarifying some of the information that I gave previously. At this moment I'm using PyTorch 1.7 pytorch_geometric 1.6.3 and torch-cluster 1.5.8 in Cuda 10.2 and python  3.6.9.  The original code was done using: pytorch_geometric 1.3.1, torch-cluster 1.4.4, PyTorch 1.2 and cuda 10.

I tried to compile different versions of torch_cluster to see in which version appears that difference of behaviour, notice that I fixed the PyTorch version and PyTorch geometric version to the newest ones. I found that version 1.5.2 of torch cluster already has this difference of behaviour. At this moment, I can not tell you if this difference appears on 1.4.5 because I was not able to compile it using the newest versions of PyTorch and PyTorch geometric. 

Also, I added in the previously shared gdrive folder the test version used in torch_geometric 1.3.1 and torch-cluster 1.4.4.

Output of the test script using  pytorch_geometric 1.6.3 and torch-cluster 1.5.8:
```
shape point cloud:  (3640, 3)
starting cpu test
len voxel_grid 3314
len consecutive_cluster 3314
len nearest 3314
starting gpu test
len voxel_grid 3314
len consecutive_cluster 3314
len nearest 3192
difference between scatter results on cpu and gpu tensor(1.1921e-07)
```

Output of the test script using  pytorch_geometric 1.3.1 and torch-cluster 1.4.4:

```
shape point cloud:  (3640, 3)
starting cpu test
len voxel_grid 3314
len consecutive_cluster 3314
len nearest 3314
starting gpu test
len voxel_grid 3314
len consecutive_cluster 3314
len nearest 3314
difference between scatter results on cpu and gpu tensor(1.1921e-07)
```

**Comment by rusty1s** [comment]
Good spot, thank you very much! Indeed, there was a bug in the parallel reduction scheme, which is now fixed in master. You can update to the latest version via:
```
pip install git+https://github.com/rusty1s/pytorch_cluster.git
```
I will craft a new bugfix release soon.

**Comment by dhorka** [comment]
Hi, have you crafted the new release? I was doing a new installation with torch1.7.1 I found the same issue.

**Comment by rusty1s** [comment]
Not yet, I plan to release a new version around mid February. For now, you will need to install from source.

**Comment by dhorka** [comment]
Hi, I think I found another use case where cpu and gpu are computing different results. I'm sharing the experiments on this [gdrive](https://drive.google.com/drive/folders/15uqAQ_-EHUASp98a_3rPSXZm5kBRPwq3?usp=sharing). I am getting these results:
```
len nearest cpu 444
len nearest gpu 291
```

**Comment by rusty1s** [comment]
Note that the `batch` vector is expected to be sorted. I will try to make this more clear in the documentation.

**Comment by dhorka** [comment]
Thanks, that was my fault. I still finish the migration of a part of my code from torch-cluster 1.4.4, and I did not see this new requirement.
