### ISSUE TITLE
Possible bug in the radius_graph method

### ISSUE THREAD

**Issue by dhorka** [rusty1s/pytorch_cluster#96]
Hello,

I was trying to port an old code that I have done with torch-cluster 1.4.4. I have found that with the current version of the radius graph method, I am obtaining different output than the one obtained with the current version. I have done a test script that computes the radius graph in cpu and gpu, and the current version of radius_graph is returning different results in gpu and cpu. Whereas, in torch-cluster 1.4.4 the results were the same in both devices. Moreover, the results obtained in the current version in gpu or cpu are different from those obtained on torch-cluster 1.4.4. You can find the test script [here](https://drive.google.com/drive/folders/1QeH_aMXEvMq5gb4S2Xm1cv5_iJs6r_6y?usp=sharing). I am not sure if this is a bug in the current version or expected behaviour. I would appreciate if you can confirm if this is a bug or not.

Test script results:

**torch-cluster==1.4.4**

```
starting cpu test
EDGE INDEX CPU:  torch.Size([2, 19841])
starting gpu test
EDGE INDEX GPU:  torch.Size([2, 19841])
```

**current version (code in master branch):**
```
starting cpu test
EDGE INDEX CPU:  torch.Size([2, 19374])
starting gpu test
EDGE INDEX GPU:  torch.Size([2, 19305])
```

Thank you,

**Comment by rusty1s** [comment]
This looks like it has to do with some numerical instabilities. Multiplying both `points` and `radius` with `10` yields equal output.

**Comment by dhorka** [comment]
When I multiply both points and radius with 10 the output that I get is:

```
starting cpu test
EDGE INDEX CPU:  torch.Size([2, 19305])
starting gpu test
EDGE INDEX GPU:  torch.Size([2, 19303])
```
They are indeed more similar, but it is not the same. If I multiply both by 100, then I get the same output in cpu and gpu. However, it is different from the output that I obtain on torch-cluster 1.4.4, is it expected to be different?

Thanks,

**Comment by rusty1s** [comment]
I see. I will look into it, but I guess the differences stem from the fact that `radius` on CPU will return the nearest neighbors, while the GPU version is non-deterministic and may return any neighbors inside `radius`.

**Comment by dhorka** [comment]
But it should return the same number, isn't it? I mean, I understand that maybe it is not returning the same neighbors,  but at least should return the same number of neighbors in both versions( 1.4.4 and the current one)

**Comment by rusty1s** [comment]
Yes, it should return the same number of neighbors. This is definitely not intended.

**Comment by rusty1s** [comment]
This is now fixed in master. I will craft a new release version soon. Thanks for reporting!

**Comment by dhorka** [comment]
Hi, I think that the problem is still here. First, I have installed the version from this commit: 2ce0f2355dcbc5b52c3b09afffcac80f68b4886b, because I had problems to install the current version on master. I get an error. It is true that if you run the test that I provided as it is you get the same numbers of neighbors. However, if you multiply by 10 the radius and the points, you are not getting the same number of neighbors:

base
```
starting cpu test
EDGE INDEX CPU:  torch.Size([2, 19305])
starting gpu test
EDGE INDEX GPU:  torch.Size([2, 19305])
```

x10
```
starting cpu test
EDGE INDEX CPU:  torch.Size([2, 19298])
starting gpu test
EDGE INDEX GPU:  torch.Size([2, 19303])
```

In addition, the number of points is different from the number of points obtained in previous releases of pytorch cluster.

**torch-cluster==1.4.4**
```
starting cpu test
EDGE INDEX CPU:  torch.Size([2, 19841])
starting gpu test
EDGE INDEX GPU:  torch.Size([2, 19841])
```

**Comment by rusty1s** [comment]
Thanks for spotting! You were indeed right. This is now (again) fixed in master, with an additional commit to fix the installation bug :)

**Comment by dhorka** [comment]
Hi @rusty1s,
 now gpu and cpu are computing the same number of points. However, I have some concerns related to the outputs that I am getting:

**base**

```
starting cpu test
EDGE INDEX CPU:  torch.Size([2, 19305])
starting gpu test
EDGE INDEX GPU:  torch.Size([2, 19305])
```
**x100**

```
starting cpu test
EDGE INDEX CPU:  torch.Size([2, 19298])
starting gpu test
EDGE INDEX GPU:  torch.Size([2, 19298])
```

As far as I understand in both experiments, I should get the same number of points. In the end, I'm just multiplying all the points for the same constant. Distances should be the same, aren't they? In fact, in previous torch cluster versions such as torch-cluster=1.4.4, I'm getting in both experiments the same output, as I expect. 

**base**

```
starting cpu test
EDGE INDEX CPU:  torch.Size([2, 19841])
starting gpu test
EDGE INDEX GPU:  torch.Size([2, 19841])
```
**x100**

```
starting cpu test
EDGE INDEX CPU:  torch.Size([2, 19841])
starting gpu test
EDGE INDEX GPU:  torch.Size([2, 19841])
```

**Comment by rusty1s** [comment]
I feel like there is nothing one can do about this. This is the result of numerical instabilities induced by floating point precision. For example, for me, there sometimes exists an edge from `pos[1016]` to `pos[1198]` and sometimes not. 

Printing the norm gives the following result:

**Base**
```python
print((pos[1016] - pos[1198]).norm().item())
0.04999995231628418
```
**x10**
```python
print((pos[1016] - pos[1198]).norm().item())
0.5
```

**Comment by dhorka** [comment]
I understand that, but in previous versions is not happening. I mean, in version 1.4.4 (I always mention this one because is the one that I was using until now) I run it several times and I always obtain the same number of edges. I run it multiplying by different constants with the same result. I have the feeling that this instability was not there before. Has been any change to the method that causes this instability? Thanks and I'm sorry for insisting so much

**Comment by rusty1s** [comment]
The reason this instability occurs is due to utilizing `nanoflann` in the CPU implementation, which performs radius-search in the open ball (not closed ball). This introduces the numerical instabilities.

**Comment by dhorka** [comment]
I suppose that GPU implementation is trying to imitate the same behavior that has CPU implementation, isn't it? Is it possible to add a flag, that allows the user to select the backend to do this radius-search? I mean, I suppose that the current version is using nanoflann for speed-up reasons, but in my case, I would prefer to have more stability rather than be quicker.

**Comment by rusty1s** [comment]
We cannot really go back to the previous version as we will loose out on TorchScript support that way. 

I understand your concerns, but the previous implementation has the exact same issue of numerical instability. It's just not present in this specific point cloud. Numerical instability does not magically disappear, since floating point precision can naturally represent way more values inside [-1, 1] than it can represent values outside of [-1, 1]. Therefore, scaling your point cloud up introduces the numerical instability, not whether we consider neighbors in the open or closed ball. I personally think that this is a non-issue.

**Comment by dhorka** [comment]
If I understood you properly, what you are saying is that I should normalize my point clouds into the range of -1 to 1, right? I am not doing that, because I prefer to choose the radius in meters, then if I normalize the point clouds I am losing this feature. But I understand what you are saying, thanks for your support!
